import mongoose, { Schema, Document } from "mongoose";

// Define the interface for description questions and answers
interface IDescription {
  question: string;
  answer: string;
  recommendation: string;
  score: number; // The score from GPT recommendation
}

// Define the interface for checklist items
interface IChecklistItem {
  id: string;
  name: string;
}

export interface ICompanyStartup extends Document {
  name: string;
  email: string;
  phone: string;
  website: string;
  logo: string; // Image URL or path
  description: IDescription[]; // Array of question-answer objects
  gpt_rating: number; // GPT rating from 0 to 100%
  generated_pitch_text: string;
  checklist: IChecklistItem[]; // List of tasks to improve rating
  verification: boolean;
}

// Define the schema
const CompanyStartupSchema: Schema = new Schema(
  {
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    phone: {
      type: String,
      required: true,
    },
    website: {
      type: String,
    },
    logo: {
      type: String, // Assuming a URL or file path for the image
    },
    description: [
      {
        question: { type: String, required: true },
        answer: { type: String, required: true }, // Answer provided by the startup
        recommendation: { type: String }, // GPT recommendations for improvements
        score: { type: Number, default: 0 }, // Score given by GPT, a numeric field
      },
    ],
    gpt_rating: {
      type: Number,
      min: 0,
      max: 100,
      default: 0, // GPT assigned rating from 0 to 100%
    },
    generated_pitch_text: {
      type: String, // Text generated by GPT for the pitch deck
    },
    checklist: [
      {
        id: { type: String, required: true },
        name: { type: String, required: true },
      },
    ],
    verification: {
      type: Boolean,
      default: false, // Initially false, set to true upon verification
    },
  },
  {
    timestamps: true, // Adds createdAt and updatedAt fields
  }
);

// Export the model
export default mongoose.model<ICompanyStartup>(
  "Company_Startup",
  CompanyStartupSchema
);
